### ISSUE TITLE
identify method/event does not set custom user properties 

### ISSUE THREAD

**Issue by bryandickson** [metro-fs/analytics-plugin-posthog#3]
https://github.com/metro-fs/analytics-plugin-posthog/blob/9fdf63a7d41cd57afbad806db1e9a8c22e3a99dc/src/index.ts#L36

References: 
https://posthog.com/docs/integrate/client/js#identifying-users 
https://posthog.com/docs/integrate/user-properties

**Comment by bryandickson** [comment]
something like this seems to work, but not sure the best wait to distinguish set vs. set_once:

`if (payload.userId) {
    var setProperties = payload.traits;
    var setOnceProperties = {}; // ???
    posthog.identify(payload.userId, setProperties, setOnceProperties);
  }`

**Comment by wlecki** [comment]
Thanks for the input! You're right, I'll prepare a small PR on Sunday evening (I'm off for the weekend ;) ).

I know that I missed the `reset` method from PostHog too. Please don't hesitate to comment if you find any other suggestions!

**Comment by bryandickson** [comment]
great thanks!

**Comment by wlecki** [comment]
Hey @bryandickson,

Please use version 1.3.1 where you can do:

```js
analytics.identify(
  'Test identify + set properties',
  {
    $set: { ... },
    $set_once: { ... }
  },
  {
    plugins: {
      all: false,
      posthog: true,
    },
  }
);
```

**Comment by bryandickson** [comment]
@wlecki I tried and it is not working the way I am calling .identify.  In the second example here, the package docs say you can call .identify like this (which is what I am doing): 

```
// Identify with additional traits
analytics.identify('xyz-123', {
  name: 'steve',
  company: 'hello-clicky'
})

```

those additional traits are not showing up for me in Posthog.

**Comment by wlecki** [comment]
Whoops, I missed your message here @bryandickson ... Sorry about that, I'll reopen and resolve that.

**Comment by M1r1k** [comment]
Hi @wlecki 

Here is PR of the fix I am using in my project :)
https://github.com/metro-fs/analytics-plugin-posthog/pull/5

**Comment by wlecki** [comment]
Thank you @M1r1k - PR approved, I'll test changes today & release the new version :)
